'use client'

import { useEffect } from 'react'
import { useRouter } from 'next/navigation'

import { DashboardLayout } from '@/components/dashboard-layout'
import { Card, CardContent, CardHeader, CardTitle, CardDescription } from '@/components/ui/card'
import { Progress } from '@/components/ui/progress'
import { Badge } from '@/components/ui/badge'

import { useStore } from '@/lib/store'

import {
  Brain,
  Shield,
  Activity,
  Clock,
  Sparkles,
  HeartPulse,
  Microscope,
  ScanLine,
  AlertTriangle,
  CheckCircle2,
} from 'lucide-react'

export default function AIInsightsPage() {
  const router = useRouter()

  const {
    currentUser,
    guestPatientId,
    patients,
    isAuthenticated,
  } = useStore()

  useEffect(() => {
    if (!isAuthenticated || currentUser?.role !== 'guest') {
      router.push('/auth/guest')
    }
  }, [isAuthenticated, currentUser, router])

  const patient = patients.find((p) => p.id === guestPatientId)

  if (!patient || !patient.aiAnalysis) return null

  const confidence = patient.aiAnalysis.confidence || 87

  const risk = patient.aiAnalysis.riskLevel || 'moderate'

  return (
    <DashboardLayout role="patient">
      <div className="max-w-6xl mx-auto space-y-6">

        {/* HEADER */}
        <div>
          <h1 className="text-3xl font-bold flex items-center gap-3">
            <Brain className="h-8 w-8 text-primary" />
            AI Insights
          </h1>

          <p className="text-muted-foreground mt-2">
            Advanced AI-powered breast scan analytics and medical insights.
          </p>
        </div>

        {/* TOP STATS */}
        <div className="grid grid-cols-1 md:grid-cols-3 gap-6">

          <Card>
            <CardContent className="pt-6">
              <div className="flex items-center justify-between mb-4">
                <Brain className="h-8 w-8 text-primary" />
                <Badge>{confidence}%</Badge>
              </div>

              <h3 className="font-semibold text-lg">
                AI Confidence
              </h3>

              <p className="text-sm text-muted-foreground mb-4">
                Prediction confidence generated by AI model.
              </p>

              <Progress value={confidence} />
            </CardContent>
          </Card>

          <Card>
            <CardContent className="pt-6">
              <div className="flex items-center justify-between mb-4">
                <Shield className="h-8 w-8 text-primary" />

                <Badge
                  variant={
                    risk === 'high'
                      ? 'destructive'
                      : risk === 'moderate'
                      ? 'secondary'
                      : 'default'
                  }
                >
                  {risk.toUpperCase()}
                </Badge>
              </div>

              <h3 className="font-semibold text-lg">
                Risk Assessment
              </h3>

              <p className="text-sm text-muted-foreground">
                AI evaluated overall medical risk level.
              </p>
            </CardContent>
          </Card>

          <Card>
            <CardContent className="pt-6">
              <div className="flex items-center justify-between mb-4">
                <Clock className="h-8 w-8 text-primary" />
                <Badge>2.4 sec</Badge>
              </div>

              <h3 className="font-semibold text-lg">
                Processing Time
              </h3>

              <p className="text-sm text-muted-foreground">
                Time required for AI scan analysis.
              </p>
            </CardContent>
          </Card>
        </div>

        {/* AI FINDINGS */}
        <Card>
          <CardHeader>
            <CardTitle className="flex items-center gap-2">
              <Microscope className="h-5 w-5 text-primary" />
              AI Findings Summary
            </CardTitle>

            <CardDescription>
              Key patterns identified from the uploaded scan.
            </CardDescription>
          </CardHeader>

          <CardContent className="space-y-4">
            {patient.aiAnalysis.findings.map((finding, index) => (
              <div
                key={index}
                className="flex items-start gap-3 p-4 rounded-xl bg-muted/40 border"
              >
                <div className="w-8 h-8 rounded-full bg-primary/10 flex items-center justify-center text-primary font-semibold">
                  {index + 1}
                </div>

                <div>
                  <p className="font-medium">{finding}</p>

                  <p className="text-sm text-muted-foreground mt-1">
                    AI detected this pattern during image processing and feature extraction.
                  </p>
                </div>
              </div>
            ))}
          </CardContent>
        </Card>

        {/* SCAN ANALYTICS */}
        <div className="grid grid-cols-1 lg:grid-cols-2 gap-6">

          <Card>
            <CardHeader>
              <CardTitle className="flex items-center gap-2">
                <ScanLine className="h-5 w-5 text-primary" />
                Scan Analytics
              </CardTitle>
            </CardHeader>

            <CardContent className="space-y-4">

              <div className="flex justify-between">
                <span className="text-muted-foreground">
                  Scan Type
                </span>

                <span className="font-medium">
                  {patient.scanType}
                </span>
              </div>

              <div className="flex justify-between">
                <span className="text-muted-foreground">
                  Scan Quality
                </span>

                <span className="font-medium">
                  Excellent
                </span>
              </div>

              <div className="flex justify-between">
                <span className="text-muted-foreground">
                  AI Model Version
                </span>

                <span className="font-medium">
                  OncoScanXAI v2.1
                </span>
              </div>

              <div className="flex justify-between">
                <span className="text-muted-foreground">
                  Analysis Status
                </span>

                <span className="font-medium text-green-600">
                  Completed
                </span>
              </div>
            </CardContent>
          </Card>

          <Card>
            <CardHeader>
              <CardTitle className="flex items-center gap-2">
                <HeartPulse className="h-5 w-5 text-primary" />
                Health Insights
              </CardTitle>
            </CardHeader>

            <CardContent className="space-y-4">

              <div className="flex items-start gap-3">
                <CheckCircle2 className="h-5 w-5 text-green-600 mt-0.5" />

                <p className="text-sm">
                  Early detection significantly improves treatment success rates.
                </p>
              </div>

              <div className="flex items-start gap-3">
                <Sparkles className="h-5 w-5 text-primary mt-0.5" />

                <p className="text-sm">
                  Regular screening and AI-assisted analysis help improve diagnostic accuracy.
                </p>
              </div>

              <div className="flex items-start gap-3">
                <AlertTriangle className="h-5 w-5 text-yellow-600 mt-0.5" />

                <p className="text-sm">
                  Always consult a certified healthcare professional for final medical decisions.
                </p>
              </div>

            </CardContent>
          </Card>
        </div>

        {/* AI RECOMMENDATION */}
        <Card className="border-primary/20">
          <CardHeader>
            <CardTitle>
              AI Recommendation Engine
            </CardTitle>

            <CardDescription>
              Generated recommendation based on scan analysis.
            </CardDescription>
          </CardHeader>

          <CardContent>
            <div className="p-5 rounded-2xl bg-primary/5 border border-primary/20">
              <p className="leading-7">
                {patient.aiAnalysis.recommendation}
              </p>
            </div>
          </CardContent>
        </Card>

      </div>
    </DashboardLayout>
  )
}